/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gerenciador.views;

import br.com.gerenciador.dao.LoginDAO;
import br.com.gerenciador.entidades.Usuario;
import br.com.gerenciador.views.adm.Principal_Diretor;
import br.com.gerenciador.views.prof.Principal_Professor;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Victor
 */
public class Tela_Login extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Login
     */
    public Tela_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPasswordSenha = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuário:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(290, 270, 50, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Senha:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(290, 330, 40, 14);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gerenciador/views/img/gerenciadorescolar.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 0, 450, 250);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gerenciador/views/img/usuarioo.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(250, 290, 32, 30);

        jTextFieldUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextFieldUsuario);
        jTextFieldUsuario.setBounds(290, 290, 190, 30);

        jButton2.setBackground(new java.awt.Color(51, 255, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Acessar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(290, 400, 190, 30);

        jPasswordSenha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPasswordSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordSenhaKeyPressed(evt);
            }
        });
        jPanel1.add(jPasswordSenha);
        jPasswordSenha.setBounds(290, 350, 190, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gerenciador/views/img/senha-32.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(250, 350, 40, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gerenciador/views/img/degrade.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 750, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Usuario u = new Usuario();
        u.setUsuario(jTextFieldUsuario.getText());
        u.setSenha(jPasswordSenha.getText());
        LoginDAO ld = new LoginDAO();
        try {
            u = ld.validaLogin(u);
            switch (u.getCargo()) {
                case "Diretor":
                    Principal_Diretor.idDiretor = u.getId_usuario();
                    Principal_Diretor dt = new Principal_Diretor();
                    Principal_Diretor.jMenuItemCadastroUsuario.setEnabled(true);
                    dt.setVisible(true);
                    dispose();
                    break;
                case "Professor":
                    Principal_Professor.idProfessor = u.getId_usuario();
                    Principal_Professor pr = new Principal_Professor();
                    pr.setVisible(true);
                    dispose();
                    break;
                case "Coordenador":
                        Principal_Diretor.idDiretor = u.getId_usuario();
                        Principal_Diretor pd = new Principal_Diretor();
                        Principal_Diretor.jMenuItemCadastroUsuario.setEnabled(false);
                        pd.setVisible(true);
                        dispose();
                        break;
                default:
                    JOptionPane.showMessageDialog(null, "Usuário não cadastrado!");
                    break;
            }

        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed

    }//GEN-LAST:event_jButton2KeyPressed

    private void jPasswordSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordSenhaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            Usuario u = new Usuario();
            u.setUsuario(jTextFieldUsuario.getText());
            u.setSenha(jPasswordSenha.getText());
            LoginDAO ld = new LoginDAO();
            try {
                u = ld.validaLogin(u);
                switch (u.getCargo()) {
                    case "Diretor":
                        Principal_Diretor.idDiretor = u.getId_usuario();
                        Principal_Diretor dt = new Principal_Diretor();
                        Principal_Diretor.jMenuItemCadastroUsuario.setEnabled(true);
                        dt.setVisible(true);
                        dispose();
                        break;
                    case "Professor":
                        Principal_Professor.idProfessor = u.getId_usuario();
                        Principal_Professor pr = new Principal_Professor();
                        pr.setVisible(true);
                        dispose();
                        break;
                    case "Coordenador":
                        Principal_Diretor.idDiretor = u.getId_usuario();
                        Principal_Diretor pd = new Principal_Diretor();
                        Principal_Diretor.jMenuItemCadastroUsuario.setEnabled(false);
                        pd.setVisible(true);
                        dispose();
                        break;
                    default:
                        JOptionPane.showMessageDialog(null, "Usuário não cadastrado!");
                        break;
                }

            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_jPasswordSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordSenha;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
