/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gerenciador.views.prof;

import br.com.gerenciador.dao.Atividades_AvaliativasDao;
import br.com.gerenciador.dao.MateriaDao;
import br.com.gerenciador.dao.TurmasDao;
import br.com.gerenciador.entidades.Atividades_Avaliativas;
import br.com.gerenciador.entidades.Calendario;
import java.awt.Dimension;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Victor
 */
public class ListAtividadesAvaliativas extends javax.swing.JInternalFrame {

    /**
     * Creates new form AtividadesAvaliativas
     */
    public ListAtividadesAvaliativas() throws SQLException {
        initComponents();

        
        readJTableAtividadas();
    }

    public void setPosition() {

        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);

    }

    

    public void readJTableAtividadas() throws SQLException {
        DefaultTableModel modelo = (DefaultTableModel) jTableAtividades.getModel();

        modelo.setNumRows(0);

        Atividades_AvaliativasDao aad = new Atividades_AvaliativasDao();
        for (Atividades_Avaliativas aa : aad.readAtividades()) {
            modelo.addRow(new Object[]{
                aa.getId_atividade(),
                aa.getMateria(),
                aa.getTurma(),
                aa.getData(),
                aa.getObservacao()

            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAtividades = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButtonFechar = new javax.swing.JButton();
        jButtonNovaAtividade = new javax.swing.JButton();
        jButtonAlterarAtividade = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonAtualizar1 = new javax.swing.JButton();

        setIconifiable(true);
        setTitle("Atividades Avaliativas");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTableAtividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Matéria", "Turma", "Data", "Observação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableAtividades);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonFechar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jButtonNovaAtividade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonNovaAtividade.setText("Nova Atividade");
        jButtonNovaAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovaAtividadeActionPerformed(evt);
            }
        });

        jButtonAlterarAtividade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonAlterarAtividade.setText("Alterar Atividade");
        jButtonAlterarAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarAtividadeActionPerformed(evt);
            }
        });

        jButtonAtualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jButtonAtualizar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonAtualizar1.setText("Excluir Atividade");
        jButtonAtualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNovaAtividade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAlterarAtividade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(jButtonAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(jButtonAtualizar1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonNovaAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAlterarAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAtualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(jButtonFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        dispose();
        Principal_Professor.jMenuItemNovaAtividade.setEnabled(true);
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonAlterarAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarAtividadeActionPerformed
        Atividades_Avaliativas aa = new Atividades_Avaliativas();
        if (jTableAtividades.getSelectedRow() != -1) {
            aa.setId_atividade((int) jTableAtividades.getValueAt(jTableAtividades.getSelectedRow(), 0));
            aa.setObservacao(jTableAtividades.getValueAt(jTableAtividades.getSelectedRow(), 4).toString());
        }
        
        Atividade_Avaliativa aaV = new Atividade_Avaliativa(aa);
        
        Principal_Professor.jDesktopPane_Professor.add(aaV);
        aaV.setVisible(true);
        aaV.setPosition();
        jButtonAlterarAtividade.setEnabled(false);
        jButtonAtualizar.setEnabled(false);
        jButtonFechar.setEnabled(false);
        jButtonNovaAtividade.setEnabled(false);
    }//GEN-LAST:event_jButtonAlterarAtividadeActionPerformed

    private void jButtonNovaAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovaAtividadeActionPerformed
        Atividade_Avaliativa aa = new Atividade_Avaliativa();
        Principal_Professor.jDesktopPane_Professor.add(aa);
        aa.setVisible(true);
        aa.setPosition();
        jButtonAlterarAtividade.setEnabled(false);
        jButtonAtualizar.setEnabled(false);
        jButtonFechar.setEnabled(false);
        jButtonNovaAtividade.setEnabled(false);
    }//GEN-LAST:event_jButtonNovaAtividadeActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        try {
            readJTableAtividadas();
        } catch (SQLException ex) {
            Logger.getLogger(ListAtividadesAvaliativas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jButtonAtualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizar1ActionPerformed
        Atividades_Avaliativas aa = new Atividades_Avaliativas();
        if (jTableAtividades.getSelectedRow() != -1) {
            aa.setId_atividade((int) jTableAtividades.getValueAt(jTableAtividades.getSelectedRow(), 0));
            Atividades_AvaliativasDao aad = new Atividades_AvaliativasDao();
            try {
                aad.deleteAtividade(aa.getId_atividade());
                JOptionPane.showMessageDialog(null, "Atividade excluída com sucesso!");
                readJTableAtividadas();
            } catch (SQLException ex) {
                Logger.getLogger(ListAtividadesAvaliativas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonAtualizar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButtonAlterarAtividade;
    public static javax.swing.JButton jButtonAtualizar;
    public static javax.swing.JButton jButtonAtualizar1;
    public static javax.swing.JButton jButtonFechar;
    public static javax.swing.JButton jButtonNovaAtividade;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAtividades;
    // End of variables declaration//GEN-END:variables
}
