/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gerenciador.views.prof;

/**
 *
 * @author Victor
 */
import br.com.gerenciador.dao.PermutaAulasDao;
import br.com.gerenciador.dao.UsuarioDao;
import br.com.gerenciador.entidades.Usuario;
import br.com.gerenciador.views.adm.AlterarDados;
import br.com.gerenciador.views.Tela_Login;
import br.com.gerenciador.views.adm.Relatorio_HorarioAulas;
import java.awt.Color;
import java.awt.Graphics;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class Principal_Professor extends javax.swing.JFrame {

    public static int idProfessor;
    
    /**
     * Creates new form Diretor_Tela
     * @throws java.sql.SQLException
     */
    public Principal_Professor() throws SQLException {
        initComponents();

        setExtendedState(MAXIMIZED_BOTH);
        PermutaAulasDao pad = new PermutaAulasDao();
        
        if(pad.solicitacaoPermuta()){
            jMenuSolicitacaoDePermuta.setEnabled(true);
            jMenuSolicitacaoDePermuta.setText("Nova Solicitação");
        }else{
            jMenuSolicitacaoDePermuta.setEnabled(false);
        }
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane_Professor = new javax.swing.JDesktopPane(){
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.setColor(Color.white);
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemNovaAtividade = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemPermuta = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuConfig = new javax.swing.JMenu();
        jMenuItemAlteraDados = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuSolicitacaoDePermuta = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane_Professor.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gerenciador/views/img/plano.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(222, 222));

        jDesktopPane_Professor.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane_ProfessorLayout = new javax.swing.GroupLayout(jDesktopPane_Professor);
        jDesktopPane_Professor.setLayout(jDesktopPane_ProfessorLayout);
        jDesktopPane_ProfessorLayout.setHorizontalGroup(
            jDesktopPane_ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 818, Short.MAX_VALUE)
        );
        jDesktopPane_ProfessorLayout.setVerticalGroup(
            jDesktopPane_ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(42, 106, 226));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gerenciador/views/img/turma.png"))); // NOI18N
        jMenu1.setText("Atividades Avaliativas");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItemNovaAtividade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gerenciador/views/img/add.png"))); // NOI18N
        jMenuItemNovaAtividade.setText("Nova Atividade Avaliativa");
        jMenuItemNovaAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNovaAtividadeActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemNovaAtividade);

        jMenuBar1.add(jMenu1);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gerenciador/views/img/permuta.png"))); // NOI18N
        jMenu3.setText("Permuta de Aulas");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItemPermuta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItemPermuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gerenciador/views/img/alterar.png"))); // NOI18N
        jMenuItemPermuta.setText("Solicitar permuta de aula");
        jMenuItemPermuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPermutaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemPermuta);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gerenciador/views/img/relatorio-icone.png"))); // NOI18N
        jMenu4.setText("Relatório");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem1.setText("Horário de aulas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        jMenuConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gerenciador/views/img/configuração.png"))); // NOI18N
        jMenuConfig.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConfigActionPerformed(evt);
            }
        });

        jMenuItemAlteraDados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItemAlteraDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gerenciador/views/img/perfil.png"))); // NOI18N
        jMenuItemAlteraDados.setText("Alterar dados");
        jMenuItemAlteraDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlteraDadosActionPerformed(evt);
            }
        });
        jMenuConfig.add(jMenuItemAlteraDados);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gerenciador/views/img/sair.png"))); // NOI18N
        jMenuItem3.setText("Sair");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuConfig.add(jMenuItem3);

        jMenuBar1.add(jMenuConfig);

        jMenuSolicitacaoDePermuta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuSolicitacaoDePermuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSolicitacaoDePermutaActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Visualizar Solicitação");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuSolicitacaoDePermuta.add(jMenuItem2);

        jMenuBar1.add(jMenuSolicitacaoDePermuta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane_Professor)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane_Professor)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jMenuItemNovaAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNovaAtividadeActionPerformed
        try {
            ListAtividadesAvaliativas aa = new ListAtividadesAvaliativas();
            jDesktopPane_Professor.add(aa);
            aa.setVisible(true);
            jMenuItemNovaAtividade.setEnabled(false);
            aa.setPosition();
        } catch (SQLException ex) {
            Logger.getLogger(Principal_Professor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuItemNovaAtividadeActionPerformed

    private void jMenuItemPermutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPermutaActionPerformed
        Permuta_Aulas pa =  new Permuta_Aulas();
        jDesktopPane_Professor.add(pa);
        pa.setVisible(true);
        pa.setPosition();
        
        jMenuItemPermuta.setEnabled(false);
    }//GEN-LAST:event_jMenuItemPermutaActionPerformed

    private void jMenuSolicitacaoDePermutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSolicitacaoDePermutaActionPerformed
        
    }//GEN-LAST:event_jMenuSolicitacaoDePermutaActionPerformed

    private void jMenuConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConfigActionPerformed
    }//GEN-LAST:event_jMenuConfigActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            Nova_Solicitacao ns = new Nova_Solicitacao();
            
            jDesktopPane_Professor.add(ns);
            ns.setVisible(true);
            ns.setPosition();
            
            jMenuSolicitacaoDePermuta.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(Principal_Professor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItemAlteraDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlteraDadosActionPerformed
        try {
            UsuarioDao ud = new UsuarioDao();
            Usuario u = ud.buscaDadosUsuario(idProfessor);

            AlterarDados ad = new AlterarDados(u);

            jDesktopPane_Professor.add(ad);
            ad.setVisible(true);
            ad.setPosition();
        } catch (SQLException ex) {
            Logger.getLogger(Principal_Professor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemAlteraDadosActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Tela_Login tl = new Tela_Login();
        tl.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Relatorio_HorarioAulas rha = new Relatorio_HorarioAulas();
        jDesktopPane_Professor.add(rha);
        rha.setVisible(true);
        rha.setPosition();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {

        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Principal_Professor().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Principal_Professor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane jDesktopPane_Professor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConfig;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    public static javax.swing.JMenuItem jMenuItemAlteraDados;
    public static javax.swing.JMenuItem jMenuItemNovaAtividade;
    public static javax.swing.JMenuItem jMenuItemPermuta;
    public static javax.swing.JMenu jMenuSolicitacaoDePermuta;
    // End of variables declaration//GEN-END:variables
}
